projection: projection.cpp
	g++ -o $@ $<

projection_submit: projection_submit.cpp
	g++ -o $@ $<

refrection: refrection.cpp
	g++ -o $@ $<

conter_clockwise: counter_clockwise.cpp
	g++ -o $@ $<

conter_clockwise_submit: counter_clockwise_submit.cpp
	g++ -o $@ $<

test: test.cpp
	g++ -o $@ $<